### ISSUE TITLE
string - literal - nomestring

### ISSUE THREAD

**Issue by programmerGM** [programmerGM/prototypeCompilerServer#10]
> string
minhavariavel 
=
'teste'
;

O correto é reconhecer:

string -> é string - token 3
minhavariavel -> nomevariavel - token 7
= ->  igual token 29
'teste' -> nomestring é o teste dentro das aspas - token 9

--- Adicional:
cout >> “Isso é um literal” -> Literal é o que está dentro da aspas DUPLAS nestes casos

**Comment by luandr** [comment]
Declaração de string é feita nomevariavel REPIDENT : TIPO ; LDVAR? não existe string variavel ="algo", e sim variavel="algo", pois não é possível declarar e utilizar diretamente.
Adicional: está reconhecendo literal. String está reconhecendo também. Vou tentar resolver a questão de variavel = "algo"

**Comment by programmerGM** [comment]
Sim, a declaração de variável é desse tipo ai, a atribuição do valor em uma variável é igual está ali em cima. Só tirar o "string" na primeira linha. 
> minhavariavel ='teste';

**Comment by luandr** [comment]
"teste". já comito

**Comment by programmerGM** [comment]
Tem que mudar, tem que fazer ficar assim:

cout >> “Isso é um literal” -> Literal é o que está dentro da aspas DUPLAS nestes casos
'a' -> Isso é um char
'teste' -> Isso é uma string.

Porque se o literal e a string forem "dessa maneira dentro da aspa duplas", como diferenciá-las?

**Comment by luandr** [comment]
`variavel="conteudo";`
Resultado
`Token | Código | Mensagem
1 | nomevariavel | 7 |  
1 | = | 29 |  
1 | nomedastring | 9 |  
1 | ; | 37 |  
2 | $ | 44`

**Comment by luandr** [comment]
Aspas simples = char. Aspas duplas = literal ou nomedastring

**Comment by programmerGM** [comment]
Como diferencia literal e string?

**Comment by luandr** [comment]
string tem que ser depois de = ou ==, tem que ver a questão do == para comparação, mas para ser string tem que ser aonde declara ela, após o =, pois para chama-la é usado o nomevariavel.
