### ISSUE TITLE
Tokens incorretos

### ISSUE THREAD

**Issue by programmerGM** [programmerGM/prototypeCompilerServer#12]
> string buscaNome{ 
return (“Linguagem C--”)
}

Retorno semelhante:

> string buscaNome (string){ 
	nome : string;
	nome = “Linguagem C--”;
	return (nome)
}

Está retornando os tokens incorretos.

**Comment by luandr** [comment]
`buscaNome` está incorreto, para nome de funcoes/variáveis deve ser tudo minusculo.
Já o `return (“Linguagem C--”)` está com problema, já identifiquei arrumo quando tiver tempo. Talvez hoje, realmente não sei se vou ter tempo.

**Comment by luandr** [comment]
Só para lembrar depois, é so ver o ultimo token se é ( e o anterior a ele se é return, se sim, o que está sendo passado entre os parênteses será uma string.
