### ISSUE TITLE
Código de teste

### ISSUE THREAD

**Issue by programmerGM** [programmerGM/prototypeCompilerServer#13]
void main {
	num, numm, soma : integer;
	soma = 0;
	
	inicio
	    cout << “Digite o valor 1: ”;
	    cin >> num;
 	    cout << “Digite o valor 2: ”;
	    cin >> numm;
	
           soma = num + numm;
	
     	   cout << “Soma: ”;
	    cin >> numm;
        fim
     }

Tem que retornar:

Linha / retorno:
1 - void
1 - main
1 - {
2 - variavel
2 - variavel
2 - variavel
2 - :
2 - integer
2 - ;
3 - variavel
3 - =
3 - inteiro
5 - inicio
6 - cout
6 - <<
6 - literal
6 ;
7 - cin
7 - >>
7 - variavel
7 - ;
Linha 8 mesma coisa da 6.
Linha 9 mesma coisa da 7.
11 - variavel
11 - =
11 - variavel
11 - + 
11 - variavel
etc......
15 - fim
16 - }
16 - $

**Comment by luandr** [comment]
```
void main {
num, numm, soma : integer;
soma = 0;

inicio
    cout << “Digite o valor 1: ”;
    cin >> num;
    cout << “Digite o valor 2: ”;
    cin >> numm;

       soma = num + numm;

 	   cout << “Soma: ”;
    cin >> numm;
    fim
 }
```

```
Linha Token Código	
1 void 2	
1 main 10	
1 { 36	
2 nomevariavel 7	
2 , 40	
2 nomevariavel 7	
2 , 40	
2 nomevariavel 7	
2 : 38	
2 integer 12	
2 ; 37	
3 nomevariavel	7	
3 = 29	
3 numerointeiro	5	
3 ;37	
5inicio13	
6cout21	
6<<31	
6literal11	
6;37	
7cin22	
7>>25	
7nomevariavel	7	
7;37	
8cout	21	
8<<	31	
8literal	11	
8;	37	
9cin	22	
9>>	25	
9nomevariavel	7	
9;	37	
11nomevariavel	7	
11=	29	
11nomevariavel	7	
11+	34	
11nomevariavel	7	
11;	37	
12cout	21	
12<<	31	
12literal	11	
12;	37	
13cout	21	
13<<31	
13nomevariavel7	
13;37	
14fim18	
15}35	
16$44
```

A IDE é para programar não pra colar o código do word lá dentro, tá funcionando se DIGITAR a "" lá dentro, se não ele copia o caracter do word/git/whatever, que é diferente de " que ele reconhece.

**Comment by programmerGM** [comment]
Tá que entregar dois códigos de exemplo pra professora, quais vão ser?

**Comment by luandr** [comment]
Já disse, ESSE está certo, é SÓ TROCAR O " QUE VC COPIAR, PELO " DIGITADO, COPIANDO ELE NÃO RECONHECE. O outro pode ser os do exemplo, eu troquei os 2 aqui pelo " correto e funcionou.
