### ISSUE TITLE
Código de teste 2

### ISSUE THREAD

**Issue by programmerGM** [programmerGM/prototypeCompilerServer#14]
void main {
	    void mostraMensagem {
		    cout << “Hello Word”;
		    return ()
              } 
 	    inicio
		    callfuncao mostraMensagem;	
	    fim
    }

----------------------------
Na linha 3 tem que retornar literal. 
Em algumas linhas está retornando nomevariavel.

**Comment by luandr** [comment]
Testei
   ```
 void mostramensagem {
	    cout << "Hello Word";
	    return ()
          } 
    inicio
	    callfuncao mostramensagem();	
    fim
}
```
Função não é chamada assim? `callfuncao mostramensagem();` passando os parâmetros em `()`?
Se não, já identifiquei também. Basta checar o ultimo token registrado se é callfuncao, se for, o próximo será nomefuncao.

**Comment by programmerGM** [comment]
Quando fizemos o manual coloquei assim pq não tem parâmetro, só olhando de novo nas definições da linguagem para confirmar, mas se a gente já fez isso quando entregamos a primeira versão do manual é porque está certo chamar a função dessa forma quando não tem nenhum parâmetro

**Comment by luandr** [comment]
Blz tem que ver isso ai, os dois testes lá rodaram aqui como está, como definimos no inicio. Vou terminar o grafo
