### ISSUE TITLE
Teste string --

### ISSUE THREAD

**Issue by luandr** [programmerGM/prototypeCompilerServer#15]
reconhece `"Linguagem C"` como string: 
```
string buscaNome{
return (“Linguagem C”)
}
```
Não reconhece
```
string buscaNome{
return (“Linguagem C--”)
}
```

**Comment by luandr** [comment]
n terei tempo para arrumar o resto, depois eu vejo

**Comment by programmerGM** [comment]
Tem que reconhecer como literal, a string é só o texto que vai ser colocado na variável, entendeu? Eu tô te falando que tem diferença faz tempo, tu faltou três aula e tá querendo teimar. String é só quando tu atribui o texto na variável:

    variavel: string;
    Variavel = "Esse texto é uma string";

Isso ai que é um string.

Em return (“Linguagem C”)  é um literal pq não está sendo atribuído a nenhuma variável.

**Comment by luandr** [comment]
Claro que não, é uma string, a função retorna string.
`string buscaNome`

**Comment by luandr** [comment]
Implementei como aspa duplas ambas, se quiser mudar fica a vontade. Eu já disse o que diferencia string, é o retorno, um recebimento de valor em variável e quando passado por parâmetro, como por exemplo:
```
void funcao("pt"){ /* comandos */ }
variavel = "var";
return("jorginho");
```
